services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true
    bind:
      $container: '@service_container'

  Danilovl\CacheResponseBundle\:
    resource: '../../../src'
    exclude:
      - '../../../src/Attribute'
      - '../../../src/DependencyInjection'
      - '../../../src/EventSubscriber/Event'
      - '../../../src/Resources'
